name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  WESNOTH_VERSION: master

permissions:
  contents: write

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v6
      with:
        path: add-ons
    - name: Lint WML
      uses: czyzby/wesnoth-wml-linter@v1
      with:
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
        spellcheck: true
        lint-flags: -K
    - name: Verify resources scope
      uses: czyzby/wesnoth-wml-scope@v1
      with:
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
        flags: -C
    - name: Verify images
      uses: czyzby/wesnoth-png-optimizer@v1
      if: always()
      continue-on-error: true
      with:
        threshold: 0
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
    - name: Commit images
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@users.noreply.github.com"
        git commit -am "ðŸ¤– Optimize $GITHUB_REPOSITORY@$GITHUB_SHA"
        git push
